const SET_USER = 'SET_USER'
const SET_MOMENTS = 'SET_MOMENTS'
const SET_PLATE_LIST = 'SET_PLATE_LIST'
const SET_MOMENT_TOTAL = 'SET_MOMENT_TOTAL'
const SET_PLATE_ID = 'SET_PLATE_ID'
const SET_COLLECT_LIST = 'SET_COLLECT_LIST'

export { SET_USER, SET_MOMENTS, SET_PLATE_LIST, SET_MOMENT_TOTAL, SET_PLATE_ID, SET_COLLECT_LIST }
