const SET_USER = 'SET_USER'
const SET_MOMENTS = 'SET_MOMENTS'
const SET_PLATE_LIST = 'SET_PLATE_LIST'
const SET_MOMENT_TOTAL = 'SET_MOMENT_TOTAL'
const SET_PLATE_ID = 'SET_PLATE_ID'
const SET_PROFILE_USER = 'SET_PROFILE_USER'
const SET_IS_PROFILE = 'SET_IS_PROFILE'
const SET_IS_LOGIN = 'SET_IS_LOGIN'
const SET_PEOPLE_INDEX = 'SET_PEOPLE_INDEX'

export {
  SET_USER,
  SET_MOMENTS,
  SET_PLATE_LIST,
  SET_MOMENT_TOTAL,
  SET_PLATE_ID,
  SET_PROFILE_USER,
  SET_IS_PROFILE,
  SET_IS_LOGIN,
  SET_PEOPLE_INDEX,
}
